/*
 * Stoatworks Labs - About window data for Vertigo.
 *
 * Normally GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json, which is the one place these facts are written
 * down. This copy is hand-written, in the generated file's exact shape,
 * because the project does not have a projects.json entry yet -- the next
 * sync-about run will overwrite it, and should, once the website page and the
 * guide exist.
 *
 * `guide` and `page` are deliberately empty rather than pointing at the URLs
 * those pages will eventually have. StoatworksAboutParams.h leaves a missing
 * link out of the button list entirely, which is the right behaviour: a button
 * that opens a 404 is worse than no button.
 *
 * `version` here is a fallback. Anything with a build step injects the real
 * one at build time and overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Vertigo";
    inline constexpr auto slug = "vertigo";
    inline constexpr auto hook = "The dolly zoom, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/vertigo";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
