/*
 * Stoatworks Labs - About window data for Vertigo.
 *
 * GENERATED by stoatworks-backend/scripts/sync-about.py on 2026-08-22. Do not
 * edit: the next sync overwrites it. The facts come from the website's
 * projects.json, which is the one place they are written down.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Vertigo";
    inline constexpr auto slug = "vertigo";
    inline constexpr auto hook = "The dolly zoom, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/vertigo/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/vertigo";
    inline constexpr auto versionFallback = "v0.1.3";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
